name: pkg / pyexasol

on:
  schedule:
    - cron: "0 6 * * 1" # Mon 06:00 UTC
  workflow_dispatch:

concurrency:
  group: pkg-pyexasol
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  build:
    uses: ./.github/workflows/_build-package.yml
    with:
      id: pyexasol
      repo: exasol/pyexasol
      kind: wheel
      package: pyexasol
