name: pkg / json-tables

on:
  schedule:
    - cron: "0 6 * * 2" # Tue 06:00 UTC
  workflow_dispatch:

concurrency:
  group: pkg-json-tables
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  build:
    uses: ./.github/workflows/_build-package.yml
    with:
      id: json-tables
      repo: exasol/json-tables
      kind: mirror
